remote-theme: niklasbuschmann/contrast@v3.0

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
#  - {file: "README.md"}

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
